---
# Source: jump-app-argocd/templates/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jump-app
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: .
    repoURL: 'https://github.com/acidonper/jump-app-gitops.git'
    targetRevision: 'feature/jump-app-dev'
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
